pull_request_rules:
  - name: Merge PRs that are ready
    conditions:
      - check-success=Check Code Style
      - check-success=Check Docs
      - check-success=Check Code Compilation
      - check-success=Run documentation tests
      - check-success=Build and Test (Scala 2.12 & JDK 8)
      - check-success=Build and Test (Scala 2.13 & JDK 8)
      - check-success=Build and Test (Scala 2.12 & JDK 11)
      - check-success=Build and Test (Scala 2.13 & JDK 11)
      - check-success=MultiJvm Test (Scala 2.12 & JDK 8)
      - check-success=MultiJvm Test (Scala 2.13 & JDK 8)
      - check-success=MultiJvm Test (Scala 2.12 & JDK 11)
      - check-success=MultiJvm Test (Scala 2.13 & JDK 11)
      - check-success=sbt Scripted Test (Scala 2.10 & JDK 8)
      - check-success=sbt Scripted Test (Scala 2.12 & JDK 8)
      - check-success=sbt Scripted Test (Scala 2.13 & JDK 11)
      - check-success=Maven Tests (JDK 8)
      - check-success=Maven Tests (JDK 11)
      - status-success=typesafe-cla-validator
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - label!=status:block-merge
      - label=status:merge-when-green
    actions:
      merge:
        method: merge

  - name: Delete the PR branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}

  - name: auto add wip
    conditions:
      # match a few flavours of wip
      - title~=^(\[wip\]( |:) |\[WIP\]( |:) |wip( |:) |WIP( |:)).*
    actions:
      label:
        add: ["status:block-merge"]
