version: ~> 1.0

language: scala

# Only build non-pushes (so PRs, API requests & cron jobs) OR tags OR forks OR main branch builds
# https://docs.travis-ci.com/user/conditional-builds-stages-jobs/
if: type != push OR tag IS present OR repo != lagom/lagom OR branch IN (master, 1.6.x, 1.5.x, 1.4.x)

addons:
  apt:
    packages:
      # Needed for `xmllint` which is used to validate pom files
      - libxml2-utils
      - xmlstarlet
      # Used to download maven xsd file
      - wget

env:
  global:
    - RUN_DROP_TRAVIS_CACHES_STAGE=false
  matrix:
    - TRAVIS_JDK=8

before_install:
  # See https://github.com/travis-ci/travis-ci/issues/4629#issuecomment-239493916
  - rm ~/.m2/settings.xml
  - curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install $(jabba ls-remote "adopt@~1.$TRAVIS_JDK.0-0" --latest=patch) && jabba use "$_" && java -Xmx32m -version

git:
  depth: false # Avoid sbt-dynver not seeing the tag

stages:
  - name: drop-travis-caches
    # to drop caches trigger a custom build with
    # env:
    #   global:
    #     - RUN_DROP_TRAVIS_CACHES_STAGE=true
    if: env(RUN_DROP_TRAVIS_CACHES_STAGE) = true
  - name: validations-and-test

jobs:
  include:
    - stage: validations-and-test
      script: bin/test-code-style
      name: "Code validations (format, binary compatibilty, etc.)"

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.jabba/jdk
    - $HOME/.sbt
    - $HOME/.m2/repository

before_cache:
  # Ensure changes to the cache aren't persisted
  - rm -rf $HOME/.ivy2/cache/com.lightbend.lagom/*
  - rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.lightbend.lagom/*
  - rm -r $HOME/.m2/repository/com/lightbend/lagom/*
  # Delete all ivydata files since ivy touches them on each build
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

notifications:
  email:
    recipients:
      secure: n0XjpDQQ9eIPvQRJvqpUvnj300XyLu80cC5+FCcmWpndN36HLUTpZs6QpjY7cXDSyPDa86UxhWf/2N1wlr+XpafTxDweolsMGRAlGgF7ojnxIgMMKDzm6NgIUlUlMJcNg39pmQzDk8PFB3hXM1sHQ+Mt1Wxyv3Fttu/JEFo3JeO3vyOXl7oC8EabxQkxCmtBNelgIvDPFgsbW6qtF69u6K2q7eI0NgL6qry4CqejUx/tCaWidMvAZ8aelx8BhrKI0FDPo0ph5fwfJqM/s3y65v63A1rdOmFweGZkMLcNP2iXe5sH8ogte+F3l4l6WSqaGdWeN/g1d16nVkZ71qYpN1Xub22Uz7iZZ1dJc89On3v7Cau6chSaVFMmjUICm261zyK5LIt4MZh1NDBPAYpniCqCtj1AntJd78KiL3qYyxEVIeG9yArA9c3JHjBbvxCC5j6VGJiZRiRwx7LH+DbO3bxvsy71/Pf/qgHmk1+373uXn/xkguoVyjYI/OrFKlrpZRj98+NfWOzs3/LToosdtNp0SjNkP3k4WYzlI6LVXcR67Ny5UxBIyelteFoPNMDJSchhkWtc5Q3UFxXmFQk7BxfUJp/3dQyWagre5MRt9q7sM/nvdT7UKswOfTdEjrlxDQL3uwgdvGWedOehqdoaQ8/+dmBFDakh6fp41V/fW/8=
    on_success: never
    on_failure: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2aa0aeda88d31fe293d4
    on_success: change
    on_failure: always
    on_start: never
